function DatasetList = GetArtificialDatasetList(Options)
% Standalone function for DatasetList setting
% DatasetList -  cell-array with the following structure:
%   * Dataset Name (string)
%   * Dataset Loading File(string of function handle);
%   * Parameters (struct)

ArtDataDir = [Options.DataDir 'artificial/'];

DataParams.BoatParams.Dir = ArtDataDir;
DataParams.BoatParams.Centering = 1;
DataParams.BoatParams.Normalization = 1;

DataParams.EasyDoughnutParams.Dir = ArtDataDir;
DataParams.EasyDoughnutParams.Centering = 1;
DataParams.EasyDoughnutParams.Normalization = 1;

DataParams.DiffDoughnutParams.Dir = ArtDataDir;
DataParams.DiffDoughnutParams.Centering = 1;
DataParams.DiffDoughnutParams.Normalization = 1;

DataParams.FlameParams.Dir = ArtDataDir;
DataParams.FlameParams.Centering = 1;
DataParams.FlameParams.Normalization = 1;

DataParams.HalfringParams.Dir = ArtDataDir;
DataParams.HalfringParams.Centering = 1;
DataParams.HalfringParams.Normalization = 1;

DataParams.NoisyLinesParams.Dir = ArtDataDir;
DataParams.NoisyLinesParams.Centering = 1;
DataParams.NoisyLinesParams.Normalization = 1;

DataParams.PetalsParams.Dir = ArtDataDir;
DataParams.PetalsParams.Centering = 1;
DataParams.PetalsParams.Normalization = 1;

DataParams.RegularParams.Dir = ArtDataDir;
DataParams.RegularParams.Centering = 1;
DataParams.RegularParams.Normalization = 1;

DataParams.SaturnParams.Dir = ArtDataDir;
DataParams.SaturnParams.Centering = 1;
DataParams.SaturnParams.Normalization = 1;

DataParams.SpiralParams.Dir = ArtDataDir;
DataParams.SpiralParams.Centering = 1;
DataParams.SpiralParams.Normalization = 1;




DatasetList = {...
    'Boat_eq' @boatLoader, DataParams.BoatParams;...
%     'Boat_less' @boatLoader, DataParams.BoatParams;...
%     'Boat_gr' @boatLoader, DataParams.BoatParams;...
    'Boat_rand' @boatLoader, DataParams.BoatParams;...
    
    'EasyDoughnut_eq' @easydoughnutLoader, DataParams.EasyDoughnutParams;...
%     'EasyDoughnut_less' @easydoughnutLoader, DataParams.EasyDoughnutParams;...
%     'EasyDoughnut_gr' @easydoughnutLoader, DataParams.EasyDoughnutParams;...
    'EasyDoughnut_rand' @easydoughnutLoader, DataParams.EasyDoughnutParams;...
    
    'DiffDoughnut_eq' @diffdoughnutLoader, DataParams.DiffDoughnutParams;...
%     'DiffDoughnut_less' @diffdoughnutLoader, DataParams.DiffDoughnutParams;...
%     'DiffDoughnut_gr' @diffdoughnutLoader, DataParams.DiffDoughnutParams;...
    'DiffDoughnut_rand' @diffdoughnutLoader, DataParams.DiffDoughnutParams;...
    
    'Flame_eq' @flameLoader, DataParams.FlameParams;...
%     'Flame_less' @flameLoader, DataParams.FlameParams;...
%     'Flame_gr' @flameLoader, DataParams.FlameParams;...
    'Flame_rand' @flameLoader, DataParams.FlameParams;...
    
    'Halfring_eq' @halfringLoader, DataParams.HalfringParams;...
%     'Halfring_less' @halfringLoader, DataParams.HalfringParams;...
%     'Halfring_gr' @halfringLoader, DataParams.HalfringParams;...
    'Halfring_rand' @halfringLoader, DataParams.HalfringParams;...
    
    'NoisyLines_eq' @noisylinesLoader, DataParams.NoisyLinesParams;...
%     'NoisyLines_less' @noisylinesLoader, DataParams.NoisyLinesParams;...
%     'NoisyLines_gr' @noisylinesLoader, DataParams.NoisyLinesParams;...
    'NoisyLines_rand' @noisylinesLoader, DataParams.NoisyLinesParams;...
    
    'Petals_eq' @petalsLoader, DataParams.PetalsParams;...
%     'Petals_less' @petalsLoader, DataParams.PetalsParams;...
%     'Petals_gr' @petalsLoader, DataParams.PetalsParams;...
    'Petals_rand' @petalsLoader, DataParams.PetalsParams;...
    
    'Regular_eq' @regularLoader, DataParams.RegularParams;...
%     'Regular_less' @regularLoader, DataParams.RegularParams;...
%     'Regular_gr' @regularLoader, DataParams.RegularParams;...
    'Regular_rand' @regularLoader, DataParams.RegularParams;...
    
    'Saturn_eq' @saturnLoader, DataParams.SaturnParams;...
%     'Saturn_less' @saturnLoader, DataParams.SaturnParams;...
%     'Saturn_gr' @saturnLoader, DataParams.SaturnParams;...
    'Saturn_rand' @saturnLoader, DataParams.SaturnParams;...
    
    'Spiral_eq' @spiral2Loader, DataParams.SpiralParams;...
%     'Spiral_less' @spiral2Loader, DataParams.SpiralParams;...
%     'Spiral_gr' @spiral2Loader, DataParams.SpiralParams;...
    'Spiral_rand' @spiral2Loader, DataParams.SpiralParams;...
    };