function ExperimentSchemesParams = GetArtificialExperSchemeParams(varargin)
% Function Build Parameter Structure for Experiments
% ExperimentSchemesParams
%   * FillOption - option for parameters for each dataset (string)
%   * SrsFunc - cell-array of cell-arrays of ensamble source functions (string or
%   handle)
%   * SrsFuncParams - cell-array of cell-arrays of parameters for source functions
%   * EnsembleSize - number of produced partitions per each source function
%   (cell-array of double-arrays)
%   * ExperimentsNum - number of experiments performed on each dataset
%   (double array)

ExperimentSchemesParams.FillOption = 'unique';
ExperimentSchemesParams.SrcFuncs = {...
    {@kmeansEnsamble;};...
%     {@kmeansEnsamble;};...
%     {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    
    {@kmeansEnsamble;};...
%     {@kmeansEnsamble;};...
%     {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    
    {@kmeansEnsamble;};...
%     {@kmeansEnsamble;};...
%     {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    
    {@kmeansEnsamble;};...
%     {@kmeansEnsamble;};...
%     {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    
    {@kmeansEnsamble;};...
%     {@kmeansEnsamble;};...
%     {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    
    {@kmeansEnsamble;};...
%     {@kmeansEnsamble;};...
%     {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    
    {@kmeansEnsamble;};...
%     {@kmeansEnsamble;};...
%     {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    
    {@kmeansEnsamble;};...
%     {@kmeansEnsamble;};...
%     {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    
    {@kmeansEnsamble;};...
%     {@kmeansEnsamble;};...
%     {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    
    {@kmeansEnsamble;};...
%     {@kmeansEnsamble;};...
%     {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    
    };


ExperimentSchemesParams.SrcFuncsParams = {...
    {struct('kmin', 2, 'kmax', 2);};... boat
%     {struct('kmin', 3, 'kmax', 3);};...
%     {struct('kmin', 5, 'kmax', 5);};...
    {struct('kmin', 2, 'kmax', inf);};...
    
    {struct('kmin', 2, 'kmax', 2);};... easydoughnut
%     {struct('kmin', 2, 'kmax', 2);};...
%     {struct('kmin', 5, 'kmax', 5);};...
    {struct('kmin', 2, 'kmax', inf);};...
    
    {struct('kmin', 2, 'kmax', 2);};... diffdoughnut
%     {struct('kmin', 2, 'kmax', 2);};...
%     {struct('kmin', 5, 'kmax', 5);};...
    {struct('kmin', 2, 'kmax', inf);};...
    
    {struct('kmin', 2, 'kmax', 2);};... flame
%     {struct('kmin', 2, 'kmax', 2);};...
%     {struct('kmin', 5, 'kmax', 5);};...
    {struct('kmin', 2, 'kmax', inf);};...
    
    {struct('kmin', 2, 'kmax', 2);};... halfring
%     {struct('kmin', 2, 'kmax', 2);};...
%     {struct('kmin', 5, 'kmax', 5);};...
    {struct('kmin', 2, 'kmax', inf);};...
    
    {struct('kmin', 2, 'kmax', 2);};... lines
%     {struct('kmin', 2, 'kmax', 2);};...
%     {struct('kmin', 5, 'kmax', 5);};...
    {struct('kmin', 2, 'kmax', inf);};...
    
    {struct('kmin', 4, 'kmax', 4);};... petals
%     {struct('kmin', 3, 'kmax', 3);};...
%     {struct('kmin', 6, 'kmax', 6);};...
    {struct('kmin', 2, 'kmax', inf);};...
    
    {struct('kmin', 16, 'kmax', 16);};... regular
%     {struct('kmin', 10, 'kmax', 10);};...
%     {struct('kmin', 20, 'kmax', 20);};...
    {struct('kmin', 2, 'kmax', inf);};...
    
    {struct('kmin', 2, 'kmax', 2);};... saturn
%     {struct('kmin', 2, 'kmax', 2);};...
%     {struct('kmin', 5, 'kmax', 5);};...
    {struct('kmin', 2, 'kmax', inf);};...
    
    {struct('kmin', 2, 'kmax', 2);};... sprial
%     {struct('kmin', 2, 'kmax', 2);};...
%     {struct('kmin', 5, 'kmax', 5);};...
    {struct('kmin', 2, 'kmax', inf);};...
    };
ExperimentSchemesParams.EnsembleSize = {...
    [40;];...
%     [40;];...
%     [40;];...
    [40;];...
    
    [40;];...
%     [40;];...
%     [40;];...
    [40;];...
    
    [40;];...
%     [40;];...
%     [40;];...
    [40;];...
    
    [40;];...
%     [40;];...
%     [40;];...
    [40;];...
    
    [40;];...
%     [40;];...
%     [40;];...
    [40;];...
    
    [40;];...
%     [40;];...
%     [40;];...
    [40;];...
    
    [40;];...
%     [40;];...
%     [40;];...
    [40;];...
    
    [40;];...
%     [40;];...
%     [40;];...
    [40;];...
    
    [40;];...
%     [40;];...
%     [40;];...
    [40;];...
    
    [40;];...
%     [40;];...
%     [40;];...
    [40;];...
    };
ExperimentSchemesParams.ExperimentsNum = [...
    20;...
%     20;...
%     20;...
    20;...
    
    20;...
%     20;...
%     20;...
    20;...
    
    20;...
%     20;...
%     20;...
    20;...
    
    20;...
%     20;...
%     20;...
    20;...
    
    20;...
%     20;...
%     20;...
    20;...
    
    20;...
%     20;...
%     20;...
    20;...
    
    20;...
%     20;...
%     20;...
    20;...
    
    20;...
%     20;...
%     20;...
    20;...
    
    20;...
%     20;...
%     20;...
    20;...
    
    20;...
%     20;...
%     20;...
    20;...
    ];

ExperimentSchemesParams.AriLowerThreshold = [...
    0.2;...
    0.2;...
    0.2;...
    0.2;...
    
    0.2;...
    0.2;...
    0.2;...
    0.2;...
    
    0.2;...
    0.2;...
    0.2;...
    0.2;...
    
    0.2;...
    0.2;...
    0.2;...
    0.2;...
    
    0.2;...
    0.2;...
    0.2;...
    0.2;...
    
    0.2;...
    0.2;...
    0.2;...
    0.2;...
    
    0.2;...
    0.2;...
    0.2;...
    0.2;...
    
    0.2;...
    0.2;...
    0.2;...
    0.2;...
    
    0.2;...
    0.2;...
    0.2;...
    0.2;...
    
    0.2;...
    0.2;...
    0.2;...
    0.2;...
    ];
ExperimentSchemesParams.AriUpperThreshold = [...
    0.7;...
    0.7;...
    0.7;...
    0.7;...
    
    0.7;...
    0.7;...
    0.7;...
    0.7;...
    
    0.7;...
    0.7;...
    0.7;...
    0.7;...
    
    0.7;...
    0.7;...
    0.7;...
    0.7;...
    
    0.7;...
    0.7;...
    0.7;...
    0.7;...
    
    0.7;...
    0.7;...
    0.7;...
    0.7;...
    
    0.7;...
    0.7;...
    0.7;...
    0.7;...
    
    0.7;...
    0.7;...
    0.7;...
    0.7;...
    
    0.7;...
    0.7;...
    0.7;...
    0.7;...
    
    0.7;...
    0.7;...
    0.7;...
    0.7;...
    ];