function ExperimentSchemesParams = GetGeneratedExperSchemeParams(Options)
% Function Build Parameter Structure for Experiments
% ExperimentSchemesParams
%   * FillOption - option for parameters for each dataset (string)
%   * SrsFunc - cell-array of cell-arrays of ensamble source functions (string or
%   handle)
%   * SrsFuncParams - cell-array of cell-arrays of parameters for source functions
%   * EnsembleSize - number of produced partitions per each source function
%   (cell-array of double-arrays)
%   * ExperimentsNum - number of experiments performed on each dataset
%   (double array)

if Options.IsEnsembleKEqual
    kmin = Options.ClusterNum;
    kmax = Options.ClusterNum;
else
    kmin = 2;
    kmax = inf;
end

if ~isfield(Options, 'LowerARI')
    Options.LowerARI = 0.2;
end
   
if ~isfield(Options, 'UpperARI')
    Options.UpperARI = 0.8;
end

ExperimentSchemesParams.FillOption = 'equal';
ExperimentSchemesParams.SrcFuncs = {...
    {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    };
ExperimentSchemesParams.SrcFuncsParams = {...
    {struct('kmin', kmin, 'kmax', kmax);};...
    {struct('kmin', 2, 'kmax', inf);};...
    {struct('kmin', 2, 'kmax', inf);};...
    {struct('kmin', 2, 'kmax', inf);};...
    {struct('kmin', 2, 'kmax', inf);};...
    {struct('kmin', 2, 'kmax', inf);};...
    {struct('kmin', 2, 'kmax', inf);};...
    {struct('kmin', 2, 'kmax', inf);};...
    {struct('kmin', 2, 'kmax', inf);};...
    {struct('kmin', 2, 'kmax', inf);};...
    };
ExperimentSchemesParams.EnsembleSize = {...
    [40;];...
    [40;];...
    [40;];...
    [40;];...
    [40;];...
    [40;];...
    [40;];...
    [40;];...
    [40;];...
    [40;];...
    };
ExperimentSchemesParams.ExperimentsNum = [...
    20;...
    20;...
    20;...
    20;...
    20;...
    20;...
    20;...
    20;...
    20;...
    20;...
    ];
ExperimentSchemesParams.AriLowerThreshold = [...
    Options.LowerARI;...
    Options.LowerARI;...    
    Options.LowerARI;...
    Options.LowerARI;...
    Options.LowerARI;...
    Options.LowerARI;...
    Options.LowerARI;...
    Options.LowerARI;...
    Options.LowerARI;...
    Options.LowerARI;...
    ];
ExperimentSchemesParams.AriUpperThreshold = [...
    Options.UpperARI;...
    Options.UpperARI;...
    Options.UpperARI;...
    Options.UpperARI;...
    Options.UpperARI;...
    Options.UpperARI;...
    Options.UpperARI;...
    Options.UpperARI;...
    Options.UpperARI;...
    Options.UpperARI;...
    ];