function ExperimentSchemesParams = GetGeneratedPartitionExperExperSchemeParams(Options)
% Function Build Parameter Structure for Experiments
% ExperimentSchemesParams
%   * FillOption - option for parameters for each dataset (string)
%   * SrsFunc - cell-array of cell-arrays of ensamble source functions (string or
%   handle)
%   * SrsFuncParams - cell-array of cell-arrays of parameters for source functions
%   * EnsembleSize - number of produced partitions per each source function
%   (cell-array of double-arrays)
%   * ExperimentsNum - number of experiments performed on each dataset
%   (double array)

if ~isfield(Options, 'LowerARI')
    Options.LowerARI = 0.2;
end
   
if ~isfield(Options, 'UpperARI')
    Options.UpperARI = 0.8;
end


ExperimentSchemesParams.FillOption = 'unique';
ExperimentSchemesParams.SrcFuncs = {...
    {@noisePartitionEnsemble;};...
    {@noisePartitionEnsemble;};...
    {@noisePartitionEnsemble;};...
    {@noisePartitionEnsemble;};...
    {@noisePartitionEnsemble;};...
    {@noisePartitionEnsemble;};...
    {@noisePartitionEnsemble;};...
    };
ExperimentSchemesParams.SrcFuncsParams = {...
    {struct('prob', 0.1, 'type', ['random']);};...
    {struct('prob', 0.2, 'type', ['random']);};...
    {struct('prob', 0.3, 'type', ['random']);};...
    {struct('prob', 0.4, 'type', ['random']);};...
    {struct('prob', 0.5, 'type', ['random']);};...
    {struct('prob', 0.6, 'type', ['random']);};...
    {struct('prob', 0.7, 'type', ['random']);};...
    };
ExperimentSchemesParams.EnsembleSize = {...
    [40;];...
    [40;];...
    [40;];...
    [40;];...
    [40;];...
    [40;];...
    [40;];...
    };
ExperimentSchemesParams.ExperimentsNum = [...
    20;...
    20;...
    20;...
    20;...
    20;...
    20;...
    20;...
    ];
ExperimentSchemesParams.AriLowerThreshold = [...
    Options.LowerARI;...
    Options.LowerARI;...
    Options.LowerARI;...
    Options.LowerARI;...
    Options.LowerARI;...
    Options.LowerARI;...
    Options.LowerARI;...
    ];
ExperimentSchemesParams.AriUpperThreshold = [...
    Options.UpperARI;...
    Options.UpperARI;...
    Options.UpperARI;...
    Options.UpperARI;...
    Options.UpperARI;...
    Options.UpperARI;...
    Options.UpperARI;...
    ];