function DatasetList = GetGeneratedPartitionDatasetList(Options)
% Standalone function for DatasetList setting
% DatasetList -  cell-array with the following structure:
%   * Dataset Name (string)
%   * Dataset Loading File(string of function handle);
%   * Parameters (struct)

DataParams.IrisParams.Dir = [Options.DataDir 'uci/iris/'];

DataParams.PartitionGenParams.numObjects = 1500;
DataParams.PartitionGenParams.numClusters = Options.ClusterNum;
DataParams.PartitionGenParams.minObjects = 1000;


DatasetList = {...
                'PartGenerated1', @partitionGenLoader, DataParams.PartitionGenParams;...
                'PartGenerated2', @partitionGenLoader, DataParams.PartitionGenParams;...
                'PartGenerated3', @partitionGenLoader, DataParams.PartitionGenParams;...
                'PartGenerated4', @partitionGenLoader, DataParams.PartitionGenParams;...
                'PartGenerated5', @partitionGenLoader, DataParams.PartitionGenParams;...
                'PartGenerated6', @partitionGenLoader, DataParams.PartitionGenParams;...
                'PartGenerated7', @partitionGenLoader, DataParams.PartitionGenParams;...
%                 'PartGenerated8', @partitionGenLoader, DataParams.PartitionGenParams;...
%                 'PartGenerated9', @partitionGenLoader, DataParams.PartitionGenParams;...
%                 'PartGenerated10', @partitionGenLoader, DataParams.PartitionGenParams;...                
                };