function ExperimentSchemesParams = GetRealExperSchemeParams(varargin)
% Function Build Parameter Structure for Experiments
% ExperimentSchemesParams
%   * FillOption - option for parameters for each dataset (string)
%   * SrsFunc - cell-array of cell-arrays of ensamble source functions (string or
%   handle)
%   * SrsFuncParams - cell-array of cell-arrays of parameters for source functions
%   * EnsembleSize - number of produced partitions per each source function
%   (cell-array of double-arrays)
%   * ExperimentsNum - number of experiments performed on each dataset
%   (double array)

ExperimentSchemesParams.FillOption = 'unique';
ExperimentSchemesParams.SrcFuncs = {...
    {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    
    {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    
    {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    
    {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    
    {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    
    {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    
    {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    
    {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    
    {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    
    {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    
    {@kmeansEnsamble;};...
    {@kmeansEnsamble;};...
    
    };
ExperimentSchemesParams.SrcFuncsParams = {...
        %iris
        {struct('kmin', 3, 'kmax', 3);};...
        {struct('kmin', 2, 'kmax', inf);};...
%     
%         %australian
%         {struct('kmin', 2, 'kmax', 2);};...
%         {struct('kmin', 2, 'kmax', inf);};...
%     
%         % balance
%         {struct('kmin', 3, 'kmax', 3);};...
%         {struct('kmin', 2, 'kmax', inf);};...
%     
%         %breast cancer
%         {struct('kmin', 2, 'kmax', 2);};...
%         {struct('kmin', 2, 'kmax', inf);};...
%     
%         %diabetes
%         {struct('kmin', 2, 'kmax', 2);};...
%         {struct('kmin', 2, 'kmax', inf);};...
%     
%         %glass
%         {struct('kmin', 7, 'kmax', 7);};...
%         {struct('kmin', 4, 'kmax', inf);};...
%     
%     %heart
%     {struct('kmin', 2, 'kmax', 2);};...
%     {struct('kmin', 2, 'kmax', inf);};...
%     
%     %ionosphere
%     {struct('kmin', 2, 'kmax', 2);};...
%     {struct('kmin', 2, 'kmax', inf);};...
%     
    %wine
    {struct('kmin', 3, 'kmax', 3);};...
    {struct('kmin', 2, 'kmax', inf);};...
%     
%     %yeast
%     {struct('kmin', 10, 'kmax', 10);};...
%     {struct('kmin', 2, 'kmax', inf);};...
    };
ExperimentSchemesParams.EnsembleSize = {...
    [40;];...
    [40;];...
    
    [40;];...
    [40;];...
    
    [40;];...
    [40;];...
    
    [40;];...
    [40;];...
    
    [40;];...
    [40;];...
    
    [40;];...
    [40;];...
    
    [40;];...
    [40;];...
    
    [40;];...
    [40;];...
    
    [40;];...
    [40;];...
    
    [40;];...
    [40;];...
    
    [40;];...
    [40;];...
    
    };
ExperimentSchemesParams.ExperimentsNum = [...
    20;...
    20;...
    
    20;...
    20;...
    
    20;...
    20;...
    
    20;...
    20;...
    
    20;...
    20;...
    
    20;...
    20;...
    
    20;...
    20;...
    
    20;...
    20;...
    
    20;...
    20;...
    
    20;...
    20;...
    
    20;...
    20;...
    ];

ExperimentSchemesParams.AriLowerThreshold = [...
    0.2;...
    0.2;...
    
    0.2;...
    0.2;...
    
    0.2;...
    0.2;...
    
    0.2;...
    0.2;...
    
    0.2;...
    0.2;...
    
    0.2;...
    0.2;...
    
    0.2;...
    0.2;...
    
    0.2;...
    0.2;...
    
    0.2;...
    0.2;...
    ];
ExperimentSchemesParams.AriUpperThreshold = [...
    0.7;...
    0.7;...
    
    0.7;...
    0.7;...
    
    0.7;...
    0.7;...
    
    0.7;...
    0.7;...
    
    0.7;...
    0.7;...
    
    0.7;...
    0.7;...
    
    0.7;...
    0.7;...
    
    0.7;...
    0.7;...
    
    0.7;...
    0.7;...
    ];
